# Generated by Django 5.0.4 on 2024-06-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='studentID',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
    ]
